apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      securityContext:
        runAsUser: 1000880000  # Ensures the same user ID
        runAsGroup: 1000880000  # Ensures the same group ID
        fsGroup: 1000880000     # Group for mounted volumes     
      containers:
      - image: quay.io/powercloud/mongodb:latest
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /data/db
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
