apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      initContainers:
      - name: init-volume-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /data/db"]
        volumeMounts:
        - name: mongo-db
          mountPath: /data/db
      containers:
      - image: quay.io/powercloud/mongodb:latest
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
