apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: fix-permissions
          command:
            - sh
            - '-c'
            - 'chown -R 999:999 /data/db && chmod -R g+rw /data/db'
          securityContext:
            runAsUser: 0
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-db
              mountPath: /data/db
      containers:
      - image: quay.io/powercloud/mongodb:latest
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /data/db
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
