kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-external-storagecluster-ceph-rbd-shared-2  
  resources:
    requests:
      storage: 8Gi
