apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: quay.io/powercloud/mongodb:latest
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
          - name: mongo-db
            mountPath: /data/db
        securityContext:
            runAsUser: 1000      # Ensure UID matches PVC file ownership
            allowPrivilegeEscalation: false
      securityContext:
        fsGroup: 1000  
      volumes:
        - name: mongo-db
          persistentVolumeClaim:
            claimName: mongo-storage
